# Generated by Django 6.1.1 on 2026-09-18 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('crop', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=100, unique=True)),
                ('is_healthy', models.BooleanField(default=False)),
                ('symptoms', models.TextField(blank=True)),
                ('causes', models.TextField(blank=True)),
                ('treatment', models.TextField(blank=True, help_text='Recommended management/treatment steps')),
                ('image', models.ImageField(blank=True, null=True, upload_to='diseases/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'diseases',
                'db_table': 'diseases_disease',
                'ordering': ['crop', 'name'],
            },
        ),
    ]
